### ISSUE TITLE
APIConnection doesn't really throw Athenahealth exception 

### ISSUE THREAD

**Issue by thsaravana** [athenahealth/mdp#21]
`APIConnection.java`: The `APIConnection` object creation doesn't really throw `AthenahealthException`, so there is no need for the `throws` in the signature. Due to this we need to wrap the object creation with an unnecessary try-catch.

**Comment by thsaravana** [comment]
If you think this is valid, let me know. I can submit a PR.

**Comment by ndonnellan** [comment]
I'm not very familiar with Java, but you appear to be correct.
